export const fontFamilies = [
  'Arial',
  'Arial Black',
  'Arial Narrow',
  'Arial Rounded MT Bold',
  'Arial Unicode MS',
  'Calibri',
  'Candara',
  'Century Gothic',
  'Comic Sans MS',
  'Courier New',
  'Geneva',
  'Georgia',
  'Gill Sans',
  'Helvetica',
  'Impact',
  'Lucida Console',
  'Lucida Grande',
  'Lucida Sans Unicode',
  'Palatino Linotype',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
  'Webdings',
  'Wingdings'
];

// export const fontFamilies = [
//   'Arial',
//   'Verdana',
//   'Tahoma',
//   'Trebuchet MS',
//   'Times New Roman',
//   'Georgia',
//   'Courier New',
//   'Brush Script MT',
//   'Comic Sans MS',
//   'Goudy Bookletter 1911',
//   'Monospace'
// ];
