export const fontFamilies = [
  'Microsoft Sans Serif',
  'Arial',
  'Helvetica',
  'Verdana',
  'Calibri',
  'Noto',
  'Lucida Sans',
  'Gill Sans',
  'Century Gothic',
  'Candara',
  'Futara',
  'Franklin Gothic Medium',
  'Trebuchet MS',
  'Geneva',
  'Segoe UI',
  'Optima',
  'Avanta Garde',
  'Times New Roman',
  'Georgia',
  'Consolas',
  'Courier',
  'Courier New',
  'Lucida Console',
  'Lucidatypewriter',
  'Lucida Sans Typewriter',
  'Monaco',
  'Andale Mono',
  'Comic Sans',
  'Comic Sans MS',
  'Impact',
  'Jazz LET',
  'Microsoft Yi Baiti'
];
